### ISSUE TITLE
ValueBag::to_$int should not use `as`

### ISSUE THREAD

**Issue by Thomasdezeeuw** [sval-rs/value-bag#15]
It has two problems. First converting a larger integer to a smaller return the maximum value (in non-release mode), but it should return `None`, i.e. I expect the following code to work.

```rust
use value_bag::ValueBag;

fn main() {
    let value = ValueBag::from(u16::MAX);
    assert_eq!(None, value.to_u8());
}
```

But the above returns `Some(255)`. Second, it shouldn't convert signed to unsigned integers as that will also return the wrong result, i.e. the following.

```rust
use value_bag::ValueBag;

fn main() {
    let value = ValueBag::from(-123i64);
    assert_eq!(None, value.to_u64());
}
```

Returns `Some(18446744073709551493)`, again unexpected.

**Comment by Thomasdezeeuw** [comment]
Oh, and this also happens for floats.

**Comment by KodrAus** [comment]
I had some time off over the last few weeks and am just catching up on things now.

I think the surprise comes from trying to use the `to_*` methods to exhaustively check what kind of value you're looking at. The way the `to_*` methods behave is to try their best to give you what you ask for. So if you want to know if there's a key with some name that looks like a `u32` then you can get it. They're not really for exhaustively identifying what kind of data the value contains.

I left a comment in https://github.com/Thomasdezeeuw/std-logger/pull/29 about what we could do there.

**Comment by fggarcia** [comment]
Hi @KodrAus.

i only want to know if the next bug is related to this issue

```
no method named `to_str` found for struct `ValueBag<'v>` in the current scope
   --> /home/fede/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.4.12/src/kv/value.rs:460:24
    |
460 |             self.inner.to_str()
    |                        ^^^^^^ method not found in `ValueBag<'v>`

error: aborting due to previous error

```

**Comment by Thomasdezeeuw** [comment]
> I think the surprise comes from trying to use the `to_*` methods to exhaustively check what kind of value you're looking at. The way the `to_*` methods behave is to try their best to give you what you ask for. So if you want to know if there's a key with some name that looks like a `u32` then you can get it. They're not really for exhaustively identifying what kind of data the value contains.

I didn't know there weren't for exhaustive checks. However I still don't think casting should be used, the second example: going from `-123i64` to `18446744073709551493u64` (although I think it's UB, not 100% sure) is clearly not what anyone wants.

**Comment by KodrAus** [comment]
> going from -123i64 to 18446744073709551493u64

Ah ok that’s definitely unexpected. In that case maybe we could simply use `From` impls where they exist and not `as`. That would mean trying to get a `u*` from an `i*` will always be `None`.

**Comment by Thomasdezeeuw** [comment]
I also think that going from large int to a small int should return `None`, i.e. an `u16` that doesn't fit in an `u8` should return `None` not `Some(255)` as there is not indication of an error (i.e. truncation), but a completely different value is reported, which doesn't seem desirable.

**Comment by KodrAus** [comment]
We should be able to use `try_from().ok()` for all of these cases, which seems to behave in a much more obvious way so if the number is out of bounds you'll get `None`.

**Comment by KodrAus** [comment]
I've updated the casting API to only allow cases where `TryFrom` is implemented and use that. It should be a lot saner to work with!

I'll follow up in `log` with an update to its API 🙇

**Comment by Thomasdezeeuw** [comment]
Thanks @KodrAus.
