### ISSUE TITLE
Consider dev channel compilers to be nightly

### ISSUE THREAD

**Issue by eggyal** [sval-rs/value-bag#22]
The following test for nightly channel compiler in the build script should probably also accept dev channel, since features etc are typically enabled there too:

https://github.com/sval-rs/value-bag/blob/c913b2ba3fe7f3db739d1e3979d01984d0d50e90/build.rs#L29

Perhaps it's worth using something like the [rustc_version](https://crates.io/crates/rustc_version) crate here?

For information: I hit this because, when using cg_clif with nightly channel rustc, the log crate (which depends on this) compiles fine; but, when using dev channel rustc built off exactly the same commit, it failed due to bjorn3/rustc_codegen_cranelift#1168 (an explicit section name is set by ctor crate following value-bag's detection of nightly channel).

**Comment by KodrAus** [comment]
Ah I was hoping to avoid needing to pull in a crate for this, but looks like I should probably just use [`version_check`](https://github.com/SergioBenitez/version_check) 🙂 It supports the `dev` channel.
