### ISSUE TITLE
Why are u128 and i128 stored as references instead of values?

### ISSUE THREAD

**Issue by tmccombs** [sval-rs/value-bag#40]
This design means that `From<u128>`  and `From<i128>` can't be implemented. 

At first I thought it was to prevent it from increasing the size, but then I realized that Internal also has variants that store fat pointers (`&str` and   `&dyn ...`) which will be 128 bits on 64 bit platforms. 

Is it to keep the size small in 32-bit platforms?  In which case, could it use a value instead of a reference on 64-bit targets, and impl From for i128 and u128?

Or is it because of alignment? Is there an important use case where the alignment can't be more than 8 bytes (assuming https://github.com/rust-lang/rust/issues/54341 is fixed)?

**Comment by tmccombs** [comment]
After some more investigation, it appears that the size is impacted if (and only if) u128 and i128 have 16 byte alignment, which is the case for aarch64, but not (currently) for x86_64. Although, if the compiler were to layout the enum differently, it could still be 24 bytes (see https://internals.rust-lang.org/t/enum-with-tag-at-end/18062), but the alignment would still be 16 bytes, and you would still need 32 bytes to store it if it was the type of an array/vec.

**Comment by KodrAus** [comment]
Hi @tmccombs! :wave:

Ahh, I'd noticed the size increase on ARM, but hadn't put two-and-two together that the difference in alignment for 128bit numbers between x86 and ARM was the culprit. Thanks for digging in to this!

The thinking that lead to this current state was:

1. I set myself a constraint that `ValueBag` must not be larger than `String` on the stack. It's easy to just throw more variants into enums without considering their impact on overall size (`fmt::Arguments` is 48 bytes!), so wanted to make concessions to keep the size down.
2. 128bit numbers are a bit niche, and the standard use-case for this library is capturing borrowed data, so I didn't expect it to be problematic to only allow borrowed 128bit numbers.

I have been thinking of things like capturing owned strings, which will increase the size of the type, so what do you think about a Cargo feature like `owned-i128` that adds inline 128bit number support along with `From` impls? We'd then also consider `owned-string` which added `String` too?

**Comment by tmccombs** [comment]
That makes sense.

I wouldn't object to having a feature flag for that. Although, I did end up creating my own wrapper enum to allow ownership (which I needed for owned strings as well). See https://github.com/slog-rs/stdlog/pull/26/files#diff-2f5dbd891ecf8d768b1b394d2138b2c244bd8dc54ff8ad4b16325877f3709eb7R101-R106. Maybe it would make sense for a separate enum like that to be part of value-bag? I'm not sure if there are many other places that would need that though.

**Comment by tmccombs** [comment]
I had another thought about this (inspired by the [recent blog post on the x128 types](https://blog.rust-lang.org/2024/03/30/i128-layout-update.html)). 

What if the i128 and u128 were always kept inline, but stored either with a wrapped type like:

```rust
#[repr(packed(8))]
PackedI128(i128);
```

Since I don't think we ever actually need to take a reference to the i128 itself (since we could instead use a reference to a stack variable after a load).
